version: '3'
services:
  ipstack-api:
    image: gravadigital/ipstack-cache:latest
    restart: always
    container_name: ipstack-api
    depends_on:
      - ipstack-mongo
    environment:
      - SERVER_PORT=3000
      - SERVER_HOST=localhost
      - LOGGER_INFO_PATH=./info.log
      - LOGGER_INFO_LEVEL=info
      - LOGGER_FILE_MAX_SIZE=1000000
      - LOGGER_MAX_FILES=50
      - LOGGER_ERROR_PATH=./error.log
      - LOGGER_ERROR_LEVEL='error'
      - MONGODB_HOST=ipstack-mongo
      - MONGODB_PORT=27017
      - MONGODB_DB=ipstack
      - NODE_ENV=develop
      - IPSTACK_TOKEN=
      - IPSTACK_URL=http://api.ipstack.com/
  ipstack-mongo:
    image: mongo:4.0
    restart: always
    container_name: ipstack-mongo
